services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 5s
      retries: 5

  api:
    build: ../backend
    command: uvicorn main:app --host 0.0.0.0 --port ${API_PORT} --reload
    volumes:
      - ../backend:/code
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      CORS_ORIGINS: ${CORS_ORIGINS}
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      db:
        condition: service_healthy

  web:
    build: ../frontend
    command: npm run dev -- --host
    working_dir: /app
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      VITE_API_URL: http://localhost:${API_PORT}
    ports:
      - "${WEB_PORT}:5173"
    depends_on:
      - api

volumes:
  db_data:
