"""initial

Revision ID: 7aa4ef5f0e8e
Revises: 
Create Date: 2025-08-27 13:32:49.795568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aa4ef5f0e8e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('selling_points',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('epts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('selling_point_id', sa.String(), nullable=False),
    sa.Column('provider', sa.Enum('worldline', 'sumup', 'other', name='eptprovider'), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['selling_point_id'], ['selling_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('selling_point_id', sa.String(), nullable=False),
    sa.Column('ept_id', sa.String(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('card_last4', sa.String(length=4), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_row_hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ept_id'], ['epts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selling_point_id'], ['selling_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_row_hash', name='uix_source_hash')
    )
    op.create_index('ix_transactions_event_occured', 'transactions', ['event_id', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_event_occured', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('epts')
    op.drop_table('selling_points')
    op.drop_table('events')
    # ### end Alembic commands ###
